name: Alf.io build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        postgresql: ['9.6','10','11','12']
    steps:
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
        restore-keys: |
          ${{ runner.os }}-gradlew-
    - uses: harmon758/postgresql-action@v1
      with:
        postgresql version: ${{ matrix.postgresql }}
        postgresql db: 'alfio'
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew build jacocoTestReport -Dspring.profiles.active=travis -Ddbenv=PGSQL-TRAVIS -Dpgsql${{ matrix.postgresql }}
  
  upload-to-coveralls:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Upload to Coveralls
        run: ./gradlew coveralls
      
